development:
  adapter: postgresql
  username: pg
  password: 
  database: kwisspjax

test:
  adapter: postgresql
  username: kwiss
  password: kwiss
  database: kwisspjax

production:
  adapter: postgresql
  username: kwiss
  password: kwiss
  database: kwissprod